### ISSUE TITLE
Enable Cirrus CI

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/perl-alien-patchelf#4]
We lost Cirrus CI in the move to the PerlAlien organisation (same process as for https://github.com/PerlAlien/Alien-Build/issues/222 ).  

It would be useful to re-enable it.  The build requirements for the aliens often differ on freebsd systems (e.g. clang compiler on recent versions, gmake plugin required).  patchelf is no different.  

I could do it directly but it seems to be applied across the whole org in the GitHub settings.

CC @plicease

**Comment by plicease** [comment]
sorry I dropped the ball here will try to figure out what went wrong here.  I had it enabled on core AB, but lost it when I moved from @perl5-alien to @perlAlien.  I ended up deciding it wasn't necessary for core AB, but kept it for FFI-Platypus which is in @PerlFFI (had a similar move from @perl5-ffi), so I will try to remember what I need to do to re-enable.

**Comment by plicease** [comment]
![image](https://user-images.githubusercontent.com/354009/168120472-9e784c3c-8301-4503-ad02-f734bf655226.png)

I've added this repo to the list that cirrus has access to can you try it now?

**Comment by shawnlaffan** [comment]
Thanks for doing that.  The most recent push has triggered a Cirrus build.
